### ISSUE TITLE
Environment creation without description

### ISSUE THREAD

**Issue by liamcoatman** [facultyai/faculty#130]
I create a new environment with `description=None` (the default). When I then call the `list` method on the environment client I get a marshmallow validation error because the type of the `description` field in the `EnvironmentSchema` is `fields.String`. Adding `allow_none=True` to the `description` field fixes the problem (this is used in `EnvironmentCreateUpdateSchema`). However, environments created using the client without descriptions have `description=None` whereas environments created through the UI have `description=''`.

**Comment by mociarain** [comment]
Fixed by: https://github.com/facultyai/faculty/pull/142
