### ISSUE TITLE
attr.s / attr.ib or attrs / attrib

### ISSUE THREAD

**Issue by acroz** [facultyai/faculty#141]
We've started using `attrs` in preference to `namedtuple` in new code in the library, in particular in:

* `faculty/context.py`
* `faculty/clients/model.py`

`attrs` provides two bindings to their class decorator and attribute builder function, with `attr.s` and `attr.ib` being the recommended interface and `attrs` and `attrib` (imported from `attr`) being the alternative:

https://www.attrs.org/en/stable/overview.html#on-the-attr-s-and-attr-ib-names

I initially used the latter as their sarcastic comment on 'serious business aliases' (which I seem to remember used to be more condescending in an earlier version of the docs) annoyed me, but since @zblz said he prefers the recommended interface (see #140 ) I thought I'd ask others' opinions, especially as this is likely to set a precedent for this and other open source libraries we develop.

AFAICT the main points are:

* For `attr.s` / `attr.ib`:
  * More concise
  * Availability of the `attr` module provides access to utility functions like `attr.evolve`
* For `attrs` / `attrib`:
  * Arguably more 'Pythonic' naming

**Comment by mociarain** [comment]
I prefer `attrs / attrib` slightly

**Comment by tomas-milata** [comment]
I prefer `attr.s / attr.ib` slightly

**Comment by srstevenson** [comment]
I have a mild preference for `attrs`/`attrib` as more Pythonic (and because of the condescension in the `attrs` documentation), but don't object to `attr.s`/`attr.ib`.

**Comment by acroz** [comment]
Since there's a marginal preference for the status quo, let's leave it with `attrs` / `atrrib`.
