### ISSUE TITLE
Can't use faculty.datasets natively with pathlib

### ISSUE THREAD

**Issue by snakch** [facultyai/faculty#148]
At the moment, it looks like we have to convert PosixPath objects to strings before passing them to datasets functions.

**Comment by imrehg** [comment]
Looking into this, my impression is so far, that `pathlib.Path` is more aimed at local paths (and dependent on the local filesystem's properties, i.e. the separators, etc). Thus for remote path should likely not use that. Also does some path manipulation behind the scenes (such as trailing backslash removals) that throws a 🔧 in the machine, imho.

If you still wanna do things somewhat more programmatically, `os.path`  and friends might be good. But to be actually correct/better, use `posixpath`  (as the remote storage should be according to that, and thus no local setup can interfere). Something like:

```python
import posixpath as path
import faculty.datasets as datasets

dataset_path = path.join("/")
# This will be: /
print(datasets.ls(dataset_path))

dataset_path = path.join("/", 'something')
# This will be: /something
print(datasets.ls(dataset_path))

dataset_path = path.join("/", 'something', 'else')
# This will be: /something/else
print(datasets.ls(dataset_path))
```

Hope this helps!
