### ISSUE TITLE
Add long_description to setup.py

### ISSUE THREAD

**Issue by srstevenson** [facultyai/faculty#63]
Currently there is no `long_description` field in `setup.py`, which means the PyPI project page is quite sparse:
![screenshot 2019-01-28 at 15 00 18](https://user-images.githubusercontent.com/5845679/51844576-7d956300-230d-11e9-98fa-6db59a3c5353.png)

**Comment by acroz** [comment]
Did this in #160 - review would be appreciated!

**Comment by acroz** [comment]
This is solved in #160.
